### ISSUE TITLE
Do we need a meeting on Monday 23rd?

### ISSUE THREAD

**Issue by andrewnl** [newlif/meet#2]
We're scheduled to have a leaders' meeting this coming Monday.
I'm feeling a bit "meeting'ed out" at the moment and wondered if we needed another since David will probably be down again in a couple of weeks.
The main area I need help is in right now is in followup: putting a system in place to contact and follow up people who we have not seen for a while. 
Let me know your thoughts as to a meeting on Monday @bumo @drichsmith @ehibbert @Luke-NewLife

**Comment by ehibbert** [comment]
I guess a couple of things 

1.pastoral issues
2. Easter service. Are their details needing to be discussed

3.  For your idea of following up people is this Something that Evert could help with?  What about Melinda as well so you have a man and  woman


Sent from my HTC

----- Reply message -----

**Comment by ehibbert** [comment]
Two things. 

This was supposed to be the meeting with our wives. So we should not cancel. 

Also of we are building to be a church of 150, meeting  once a month does not support that

Sent from my HTC ----- Reply message -----

**Comment by andrewfn** [comment]
I'm good with meeting if other people are able to come.
Those are good points Tafari. What do others think?

**Comment by Luke-NewLife** [comment]
Amanda and I can both make it... do we have anyone that could help with the kids? If it's leaders and wives that would be 8 children...

**Comment by andrewnl** [comment]
We could ask Sandra if you think that could work?

**Comment by drichsmith** [comment]
Heather and I will be there. We'll put down some water and newspaper for
the kids at home before we leave.

see you tonight.
-dan

**Comment by andrewnl** [comment]
Sandra has agreed to come (although there is obviously a limit to the number of kids she can look after).

**Comment by newlif** [comment]
Posted by Tafari:
Can we take a step back. What is the objective for having prayer there. Isn't it to scope the place out.

Why don't we as leadership scope this place on a Saturday and leave prayer at normal place and time. Changing day and time is just confusing for most people
